# Increase the heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m

# Enable parallel execution and build caching for better performance
org.gradle.parallel=true
org.gradle.caching=true

# Android Gradle Plugin settings
android.useAndroidX=true
android.nonTransitiveRClass=true
